### ISSUE TITLE
SMAPI LOG

### ISSUE THREAD

**Issue by NoiseNoises** [aEnigmatic/StardewValley#1]
Filling seven chests and categorizing them, went to drop an assortment of items to fill chests and it didn't function. Log report below:

```
[Convenient Chests] This mod failed in the ControlEvents.KeyPressed event. Technical details:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ConvenientChests.CategorizeChests.Framework.ItemDataManager.CreatePrototype(Item item)
   at ConvenientChests.CategorizeChests.Framework.ItemDataManager.GetKey(Item item)
   at ConvenientChests.CategorizeChests.CategorizeChestsModule.ChestAcceptsItem(Chest chest, Item item)
   at ConvenientChests.StackToNearbyChests.StashToNearbyChestsModule.<get_acceptingFunction>b__3_0(Chest chest, Item i)
   at ConvenientChests.StackToNearbyChests.StackLogic.<>c__DisplayClass1_1.<StashToNearbyChests>b__1(Item i)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConvenientChests.StackToNearbyChests.StackLogic.StashToNearbyChests(Int32 radius, Func`3 acceptingFunction)
   at ConvenientChests.StackToNearbyChests.StashToNearbyChestsModule.TryStashNearby()
   at ConvenientChests.StackToNearbyChests.StashToNearbyChestsModule.onKeyPressed(Object sender, EventArgsKeyPressed e)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 54
```

**Comment by aEnigmatic** [comment]
Thanks. Should not happen anymore...
