### ISSUE TITLE
Errors / Bugs with Stashing Behavior

### ISSUE THREAD

**Issue by Exaxxion** [aEnigmatic/StardewValley#25]
After updating to mod version 1.6.4, the stashing logic started behaving very strangely.

When pressing the Stash From Anywhere hotkey I get this error in the SMAPI console, and only some items were moved:

```
[Convenient Chests] This mod failed in the Input.ButtonPressed event. Technical details: 
InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ConvenientChests.StashToChests.StackLogic.TryStashToChest(Chest chest, AcceptingFunction f) in D:\Projekte\rider\StardewValley\ConvenientChests\StashToChests\StackLogic.cs:line 62
   at ConvenientChests.StashToChests.StashFromAnywhereModule.StashGlobally() in D:\Projekte\rider\StardewValley\ConvenientChests\StashToChests\StashFromAnywhereModule.cs:line 35
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```

I have also noticed that inventory contents are being slid towards the left and up rows including into the hotbar. The game also thinks the inventory is full and items won't be pulled into it, until I open the screen (which seems to make it realize it has plenty of room for more items).

None of these problems occurred in mod version 1.6.3.

**Comment by aEnigmatic** [comment]
Fixed with 1.6.5 👍
